ln -s gcc.git/ABOUT-NLS
ln -s gcc.git/ChangeLog.tree-ssa
ln -s gcc.git/INSTALL
ln -s gcc.git/README.SCO
ln -s gcc.git/autom4te.cache
ln -s gcc.git/boehm-gc
ln -s gcc.git/contrib
ln -s gcc.git/fixincludes
ln -s gcc.git/gcc
ln -s gcc.git/gnattools
ln -s gcc.git/libada
ln -s gcc.git/libcpp
ln -s gcc.git/libffi
ln -s gcc.git/libgcc
ln -s gcc.git/libgfortran
ln -s gcc.git/libgomp
ln -s gcc.git/libjava
ln -s gcc.git/libmudflap
ln -s gcc.git/libobjc
ln -s gcc.git/libssp
ln -s gcc.git/libstdc++-v3
ln -s gcc.git/libtool-ldflags
ln -s gcc.git/maintainer-scripts
ln -s gcc.git/zlib
ln -s gcc-deplibs.git/gmp
ln -s gcc-deplibs.git/mpc
ln -s gcc-deplibs.git/mpfr
